config/routes.rb
Beta1::Application.routes.draw do
  root :to => "articles#index"
  resources :articles
  resources :users
  resource :session, :only => [:new, :create, :destroy]
  get '/login' => "sessions#new", :as => "login"
  get '/logout' => "sessions#destroy", :as => "logout"
end  

  #   end

app/models/article.rb
class Article < ActiveRecord::Base
  validates_presence_of :subject, :topic

  belongs_to :user
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
  attr_accessor  :password
  validates_uniqueness_of :email
  validates_length_of  :email, :within => 5..50
  #validates_format_of :email, :with => /^[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}$/i

  validates_confirmation_of :password
  validates_length_of :password, :within => 8..10
  validates_presence_of :password, :if => :password_required?

  has_one :profile
  has_many :articles, -> {order('subject, topic') }, :dependent => :destroy

  before_save :encrypt_new_password
 
    def self.authenticate(email, password)
     user = find_by_email(email)
     return user if user && user.authenticated?(password)
    end

    def authenticated?(password)
     self.hashed_password == encrypt(password)
    end

    protected
      def encrypt_new_password
        return if password.blank?
        self.hashed_password = encrypt(password)
      end

      def password_required?
         hashed_password.blank? || password.present?
      end

      def encrypt(string)
         Digest::SHA1.hexdigest(string)
      end
 #   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.  
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all.order("subject ASC, topic ASC")
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render action: 'show', status: :created, location: @article }
      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:subject, :topic, :notes, :reference, :published_at)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.authenticate(params[:email], params[:password])
      session[:user_id] = user.id
      redirect_to root_path, :notice => "Logged in successfully"
    else
      flash.now[:alert] = "Invalid login/password combination"
      render :action => 'new'
    end
  end

  def destroy
    reset_session
    redirect_to root_path, :notice => "You successfully logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end
 
 
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to articles_path, notice: 'User successfully added.'
    else
      render action: :new
    end
  end
 
  def edit
  end
 
  def update
    if @user.update(user_params)
      redirect_to articles_path, notice: 'Updated user information successfully.'
    else
      render action: 'edit'
    end
  end
 
  private
  def set_user
    @user = User.find(params[:id])
  end
 
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<%= div_for article do %>
  <h3>
    <%= link_to article.title, article %>
    <span class='actions'>
      <%= link_to "Edit", edit_article_path(article) %>
      <%= link_to "Delete", article, confirm: "Are you sure?", method: :delete %>
    </h3>
    <%= article.body %>
<% end %> 

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :topic %><br>
    <%= f.text_field :topic %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :reference %><br>
    <%= f.text_field :reference %>
  </div>
  <div class="field">
    <%= f.label :published_at %><br>
    <%= f.datetime_select :published_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Topic</th>
      <th>Notes</th>
      <th>Reference</th>
      <th>Published at</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.subject %></td>
        <td><%= article.topic %></td>
        <td><%= article.notes %></td>
        <td><%= if article.reference[0,7].eql? "http://" 
                  link_to article.reference, article.reference, target: '_blank'
                elsif article.reference[0,8].eql? "https://"
                  link_to article.reference, article.reference, target: '_blank'
                #elsif article.reference.split(//).last(4).join("").eql? ".pdf"
                  #link_to article.reference :format => :pdf
                  #link_to article.reference, article.reference, target: '_blank'  
                else 
                   article.reference
                end      
        %></td>
        <td><%= article.published_at %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<%= render @article %>

<!-- <p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @article.subject %>
</p>

<p>
  <strong>Topic:</strong>
  <%= @article.topic %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @article.notes %>
</p>

<p>
  <strong>Reference:</strong>
  <%= if @article.reference[0,7].eql? "http://" 
                  link_to @article.reference, @article.reference, target: '_blank'
                elsif @article.reference[0,8].eql? "https://"
                  link_to @article.reference, @article.reference, target: '_blank'      
                else 
                   @article.reference
                end   %>
</p>

<p>
  <strong>Published at:</strong>
  <%= @article.published_at %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>
-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Beta1</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= content_tag :p, notice, :class => 'notice' if notice.present? %>
<%= content_tag :p, alert, :class => 'alert' if alert.present? %>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
 
  <div class="field">
   <%= f.label :email %><br />
   <%= f.text_field :email %>
  </div>
  <div class="field">
   <%= f.label :password %><br />
   <%= f.password_field :password %>
  </div>
  <div class="field">
   <%= f.label :password_confirmation %><br />
   <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
   <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %> 

app/views/users/new.html.erb
<h1>New user</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %> 